/**
 * Service to interact directly with Google Gemini REST API from the browser.
 */

const GEMINI_API_KEY_STORAGE = 'biblioteca_gemini_api_key';

export function getStoredGeminiApiKey() {
  return localStorage.getItem(GEMINI_API_KEY_STORAGE) || import.meta.env.VITE_GEMINI_API_KEY || '';
}

export function saveGeminiApiKey(key) {
  const trimmed = (key || '').trim();
  if (trimmed) {
    localStorage.setItem(GEMINI_API_KEY_STORAGE, trimmed);
  } else {
    localStorage.removeItem(GEMINI_API_KEY_STORAGE);
  }
}

/**
 * Sends a RAG prompt with local document context to Google Gemini API (gemini-1.5-flash).
 * @param {string} userQuery - The question asked by the user
 * @param {Array} relevantDocs - Matching documents from IndexedDB
 * @param {Array} relevantBooks - Matching books from IndexedDB
 * @param {string} apiKey - Google Gemini API Key
 * @returns {Promise<string>} - Answer generated by Gemini
 */
export async function queryGeminiRAG(userQuery, relevantDocs = [], relevantBooks = [], apiKey) {
  const key = apiKey || getStoredGeminiApiKey();
  if (!key) {
    throw new Error('Chave da API do Gemini não configurada.');
  }

  // Construct Context string from local OCR documents
  let contextText = '';
  if (relevantDocs.length > 0) {
    contextText += `=== DOCUMENTOS DA BIBLIOTECA DO USUÁRIO ===\n`;
    relevantDocs.forEach((doc, i) => {
      contextText += `\n[Documento ${i + 1}]: "${doc.title || doc.fileName}"\n`;
      if (doc.createdDate) contextText += `Data do Documento: ${doc.createdDate}\n`;
      if (doc.ocrText) contextText += `Texto OCR:\n${doc.ocrText.slice(0, 3000)}\n`;
    });
  }

  if (relevantBooks.length > 0) {
    contextText += `\n=== LIVROS DA ESTANTE ===\n`;
    relevantBooks.forEach((book, i) => {
      contextText += `\n[Livro ${i + 1}]: "${book.title}" por ${book.author || 'Autor desconhecido'}\n`;
      if (book.description) contextText += `Descrição/Resumo: ${book.description}\n`;
      contextText += `Status: ${book.readStatus} (Pág. ${book.lastReadPage || 1} de ${book.pageCount || '?'})\n`;
    });
  }

  const systemInstruction = `Você é o Assistente de Inteligência Artificial da Biblioteca Pessoal do usuário.
Responda de forma concisa, educada e direta em português do Brasil (pt-BR).
Use strictly o contexto de documentos e livros fornecido abaixo para responder com precisão. Se encontrar valores monetários, datas ou nomes, destaque em negrito.
Se a informação não estiver no contexto, diga amigavelmente que não encontrou nos documentos cadastrados.`;

  const prompt = `${contextText}\n\n=== PERGUNTA DO USUÁRIO ===\n${userQuery}`;

  const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${key}`;

  const response = await fetch(url, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      contents: [
        {
          role: 'user',
          parts: [
            { text: `${systemInstruction}\n\n${prompt}` }
          ]
        }
      ],
      generationConfig: {
        temperature: 0.2,
        maxOutputTokens: 1000
      }
    })
  });

  if (!response.ok) {
    const errorData = await response.json().catch(() => ({}));
    const msg = errorData.error?.message || `Erro HTTP ${response.status}`;
    throw new Error(`Falha no Gemini: ${msg}`);
  }

  const data = await response.json();
  const candidateText = data.candidates?.[0]?.content?.parts?.[0]?.text;

  if (!candidateText) {
    throw new Error('A resposta do Gemini veio vazia.');
  }

  return candidateText;
}
